### ISSUE TITLE
Ui changes 

### ISSUE THREAD

**Issue by afif1400** [afif1400/docker-fibonacci#1]

**Comment by Iamgope** [comment]
@afif1400 can you explain what ui changes you want here?

**Comment by afif1400** [comment]
hey, this is how the UI looks right now...
![docker-fibonacci](https://user-images.githubusercontent.com/51887071/120081175-c3c78080-c0d9-11eb-99fa-ecbd6798cbb0.png)
pretty bad, can make it better.

**Comment by Iamgope** [comment]
fine, I will assign to me
